[2024-11-18T12:50:31.538+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-18T12:50:32.710+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_pipeline.load_weather_data manual__2024-11-18T12:38:40.329353+00:00 [queued]>
[2024-11-18T12:50:32.761+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_pipeline.load_weather_data manual__2024-11-18T12:38:40.329353+00:00 [queued]>
[2024-11-18T12:50:32.763+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 6
[2024-11-18T12:50:33.575+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): load_weather_data> on 2024-11-18 12:38:40.329353+00:00
[2024-11-18T12:50:34.564+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=617) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-18T12:50:34.569+0000] {standard_task_runner.py:72} INFO - Started process 626 to run task
[2024-11-18T12:50:34.585+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_pipeline', 'load_weather_data', 'manual__2024-11-18T12:38:40.329353+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl.py', '--cfg-path', '/tmp/tmpxuq2lniq']
[2024-11-18T12:50:34.649+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask load_weather_data
[2024-11-18T12:50:37.565+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_etl_pipeline.load_weather_data manual__2024-11-18T12:38:40.329353+00:00 [running]> on host a1d4e919f1b0
[2024-11-18T12:50:43.078+0000] {job.py:229} INFO - Heartbeat recovered after 14.70 seconds
[2024-11-18T12:50:52.406+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='naphat' AIRFLOW_CTX_DAG_ID='weather_etl_pipeline' AIRFLOW_CTX_TASK_ID='load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T12:38:40.329353+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T12:38:40.329353+00:00'
[2024-11-18T12:50:52.411+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-18T12:50:55.945+0000] {job.py:229} INFO - Heartbeat recovered after 13.04 seconds
[2024-11-18T12:50:58.044+0000] {base.py:84} INFO - Retrieving connection 'postgres_db'
[2024-11-18T12:51:03.265+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-18T12:51:08.729+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-18T12:51:08.732+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_etl_pipeline, task_id=load_weather_data, run_id=manual__2024-11-18T12:38:40.329353+00:00, execution_date=20241118T123840, start_date=20241118T125032, end_date=20241118T125108
[2024-11-18T12:51:15.231+0000] {job.py:229} INFO - Heartbeat recovered after 19.52 seconds
[2024-11-18T12:51:16.255+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-18T12:51:16.330+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-11-18T12:51:17.256+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-18T12:51:17.359+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
