[2024-11-18T12:50:31.976+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-18T12:50:32.719+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_pipeline.load_weather_data scheduled__2024-11-17T00:00:00+00:00 [queued]>
[2024-11-18T12:50:32.768+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_pipeline.load_weather_data scheduled__2024-11-17T00:00:00+00:00 [queued]>
[2024-11-18T12:50:32.771+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 6
[2024-11-18T12:50:33.823+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): load_weather_data> on 2024-11-17 00:00:00+00:00
[2024-11-18T12:50:33.959+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=614) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-18T12:50:33.972+0000] {standard_task_runner.py:72} INFO - Started process 624 to run task
[2024-11-18T12:50:33.951+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_pipeline', 'load_weather_data', 'scheduled__2024-11-17T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl.py', '--cfg-path', '/tmp/tmpgqpmq5mb']
[2024-11-18T12:50:34.061+0000] {standard_task_runner.py:105} INFO - Job 15: Subtask load_weather_data
[2024-11-18T12:50:37.555+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_etl_pipeline.load_weather_data scheduled__2024-11-17T00:00:00+00:00 [running]> on host a1d4e919f1b0
[2024-11-18T12:50:44.933+0000] {job.py:229} INFO - Heartbeat recovered after 16.91 seconds
[2024-11-18T12:50:51.624+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='naphat' AIRFLOW_CTX_DAG_ID='weather_etl_pipeline' AIRFLOW_CTX_TASK_ID='load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-17T00:00:00+00:00'
[2024-11-18T12:50:51.822+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-18T12:50:55.479+0000] {base.py:84} INFO - Retrieving connection 'postgres_db'
[2024-11-18T12:50:58.368+0000] {job.py:229} INFO - Heartbeat recovered after 14.12 seconds
[2024-11-18T12:51:03.231+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-18T12:51:08.881+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-18T12:51:08.905+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_etl_pipeline, task_id=load_weather_data, run_id=scheduled__2024-11-17T00:00:00+00:00, execution_date=20241117T000000, start_date=20241118T125032, end_date=20241118T125108
[2024-11-18T12:51:13.165+0000] {job.py:229} INFO - Heartbeat recovered after 15.36 seconds
[2024-11-18T12:51:15.139+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-18T12:51:16.220+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-11-18T12:51:16.682+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-18T12:51:16.687+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
